# Generated by Django 2.0.1 on 2024-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='将来的你定会感谢现在的自己，加油同学！', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='好好学习，天天向上', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='https://space.bilibili.com/1565906988', max_length=1000, verbose_name='访问地址'),
        ),
    ]
